✨ clinical chart - proof of concept
icgc-argo/platform-ui pull request #1831
Opened 2021-02-19 16:49 UTC by samrichca

**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Styling
- [x] New Feature

**Checklist before requesting review:**

- [ ] Matches design:

  - component sizes, spacing, and styles
  - font size, weight, colour
  - spelling has been double checked

- [ ] New uikit components have Storybook stories
- [x] Feature is minimally responsive.
- [x] Add copyrights to new files
- [ ] Manual testing of UI feature.
- [ ] Selenium test is completed and passing.

2021-02-19 17:38 UTC, samrichca commented on global/utils/common.tsx
> -const standardDate = 'YYYY-MM-DD';
when i updated date-fns this started throwing errors

2021-02-19 19:45 UTC, ciaranschutte commented on package.json
> +    "date-fns": "^2.17.0",
Did this break the other uses of `date-fns`?
'/global/utils/common.tsx'
'/components/pages/submission-system/program-dashboard/DonorDataSummary/DownloadButtons.tsx'

2021-02-19 19:47 UTC, ciaranschutte commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +import * as t from './types';
stylistically wondering if we should stick with explicitly importing like:
`import { differenceInDays, eachQuarterOfInterval, getQuarter, getYear, isAfter, isBefore, compareAsc } from 'date-fns';`

Are there benefits to using the `import * ` syntax?

2021-02-19 19:48 UTC, ciaranschutte commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +              key={_}
is this just to shut up a react warning?

2021-02-19 19:54 UTC, ciaranschutte commented on components/pages/submission-system/program-dashboard/LineChart/RangeControlBar.tsx
> +      style={{...styles.button, ...(isActive ? styles.buttonActive : {})}}
This is a different stylistically from most of the project which is using Emotion.
Is is possible to use it here?

something like:
```
<button css={css`
  background: transparent;
    border: 0 none;
    color: ${isActive? 'red' : #525767};
    cursor: 'pointer';
    display: inline-block;
    fontFamily: 'Work Sans, sans-serif';
    fontSize: 12px
    padding: 4;
    width: 25px;
   
`}...../>
```

2021-02-19 19:54 UTC, ciaranschutte commented
anything to gain from using d3?

2021-02-19 20:00 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/RangeControlBar.tsx
> +      style={{...styles.button, ...(isActive ? styles.buttonActive : {})}}
sure thing

2021-02-19 20:17 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +import * as t from './types';
If we are only using part of the library, then using the explicit imports has the potential to reduce the size of the JS files needed to be downloaded on the UI. Therefore, explicit import from bigger libraries (ie. lodash) is prefered, and should be our standard for dependencies including internal dependencies from things like `utils` and `types`

If we do use the `import * as utils from './utils';` we should not be using single letter names.

2021-02-19 20:18 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +              key={_}
I'm curious where you got this as well. Since this is JS, what value do we expect the underscore to output in this case, seems like an intriguing solution.

2021-02-19 20:24 UTC, joneubank commented on .env.schema
> +DASHBOARD_CHARTS_ENABLED=true
Lets use the word FEATURE in all our feature flag variables: `FEATURE_DASHBOARD_CHARTS_ENABLED`

Unfortunately there are many other env variables used that are not in this schema file... we should update that in the future.

2021-02-19 20:26 UTC, joneubank commented on global/config.ts
> +    DASHBOARD_CHARTS_ENABLED: publicConfig.DASHBOARD_CHARTS_ENABLED === 'true',
update to `FEATURE_DASHBOARD_CHARTS_ENABLED`

2021-02-19 20:26 UTC, joneubank commented on components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
> +          align-items: center; */
Remove instead of commenting.

2021-02-19 20:31 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +const LineChartEl = ({
Reading `El` is confusing and it appears to not be standard in the platform components. Does it stand for 'element'? Let's find a name that reflects what this component is or at very least not use the abbreviated version (full words unless very obvious names please)

2021-02-19 20:32 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +    // svg rendering made the colours darker/lighter.
👍 Let's make sure we get Kim to review the chart before we publish. Thanks for this comment to explain the change in values.

Maybe we should move these values to an external constants file for SVG chart element properties... don't need to now, but it would be useful for future charts types that need consistent styling.

2021-02-19 20:35 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
Will there be issues if other lines have more/less points?

2021-02-19 20:39 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/RangeControlBar.tsx
> +const styles = {
Take a look at how `styled` elements are made and used in other components, very similar to what you have here but can import theme properties. We may be able to include the svg colours in the theme then.

2021-02-19 20:41 UTC, joneubank requested changes
Lots of amazing work here, just called out some simple things in comments (should've grouped them as a review but I messed up...) . Thanks Sam!

2021-02-22 16:46 UTC, samrichca commented on package.json
> +    "date-fns": "^2.17.0",
it broke both but i only fixed one, good catch

2021-02-22 16:54 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +import * as t from './types';
I did indeed use explicit imports from libraries for performance/build size reasons 

Updated utils/types to be explicit imports

2021-02-22 17:00 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +              key={_}
@ciaranschutte Yeah, not supposed to use index for keys in map functions because index could change

@joneubank the underscores are from an example I started from, basically means, "this value doesn't matter". I updated the code to remove them

2021-02-22 17:08 UTC, samrichca commented
> anything to gain from using d3?

In this case no, since there's no heavy animation/customization/etc and I expect to handle the math on the backend.

@joneubank shared a great article with me: https://medium.com/@PepsRyuu/why-i-no-longer-use-d3-js-b8288f306c9a

2021-02-22 17:19 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
For this particular chart I want all lines to have the same X coordinates. Potentially in the future I'd have to account for more/less points or points being different between lines but in this case we're aggregating data into 7 buckets on the backend, so there should be 7 points, although some might have null Y coordinates (I'll check with Rosi)

2021-02-22 17:34 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
Ok checked in with her:

- All lines start at program create date
- If the user queries a date before the program create date, we'll correct it to show program create date to [present or whatever the end date was in the query]

2021-02-22 18:22 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
in this case, should we specify the number of points and their labels separate from the data?

2021-02-22 18:23 UTC, joneubank commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
Just trying to avoid mixups with the data and the desired chart appearance, in particular since it is possible to have multiple lines that are missing data points at the start/end of the time series.

2021-02-22 20:15 UTC, samrichca commented on components/pages/submission-system/program-dashboard/LineChart/LineChartEl.tsx
> +  const dataPoints = data.lines[0].points;
> in this case, should we specify the number of points and their labels separate from the data?

Yeah, I was thinking of doing this:

```
{ 
  chartType: 'molecular',
  committedDonors: 2000,
  dates: [ 7 dates in unix epoch ],
  lines: [{
    label: 'molecular lines have names',
    data: [ 7 y axis values ],
  }]
}
```

In this case there won't be any missing values, but there could be in some other line chart we eventually make. I'm not sure how general purpose I should make this UI component or the API

2021-02-24 18:38 UTC, samrichca commented on components/pages/file-repository/FacetPanel/index.tsx
> +import { FilterOption } from 'uikit/OptionsList';
this was throwing an error

2021-02-24 18:38 UTC, samrichca commented on components/pages/file-repository/FacetPanel/index.tsx
> +  const facetContainerLoadingStyle = css`
typo

2021-02-24 21:25 UTC, ciaranschutte approved these changes

2021-03-01 15:31 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart.tsx
> +  // TODO: maxY is this OR committed donors, whichever is more
This is specific to the donor page usage of the line chart, not specific to Line Charts themselves. Ideally we would keep this as a generic LineChart component to be used in several places around the platform, and we can make a specific version that includes horizontal lines that show the Committed Donors just for the Donor Dashboard.

2021-03-01 15:36 UTC, samrichca commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart.tsx
> +  // TODO: maxY is this OR committed donors, whichever is more
agreed, I wanna get it working and then make it more general purpose

2021-03-01 16:13 UTC, joneubank approved these changes
Great start to building this chart.

As discussed, this is work in progress. We plan to refactor in the future to make the LineChart a generic chart component that is provided by the UI kit, but we are building in context for now to speed up development. Future work will be done to separate it and make a generic interface for chart properties such as data/axis and labels/toggles for grid lines, etc.

2021-03-01 17:07 UTC, samrichca commented on components/pages/submission-system/program-dashboard/DonorDataSummary/DownloadButtons.tsx
> +        const now = formatDate(Date.now(), 'yyyyMMdd');
that's a good idea

2021-03-01 17:09 UTC, samrichca commented on global/utils/common.tsx
> +const dateFormat = 'yyyy-MM-d';
good catch, fixed

2021-03-01 17:29 UTC, merged