Feature/form checkbox focus blur
icgc-argo/platform-ui pull request #1952
Opened 2021-05-28 14:48 UTC by caravinci

**Description of changes**

Enables using the checkboxes' `blur` and `focus` events, and styles the `FormCheckbox` component accordingly, even when used inside a `FormControl`.

Can be tested here: https://feature-formcheckbox-focus-blur--argo-ui-storybook.netlify.app/?path=/story/uikit-form-formcheckbox--default

**Type of Change**

- [ ] Bug
- [ ] Styling
- [x] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [x] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [x] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

2021-05-28 15:07 UTC, caravinci reviewed
The usual comments, which in this PR may actually prove necessary... and hopefully useful 🙏

2021-05-28 15:07 UTC, caravinci commented on uikit/form/Checkbox/stories.tsx
> +  const [checked, setChecked] = useState(false);
makes the component actually interactive in the story

2021-05-28 15:07 UTC, caravinci commented on uikit/form/Checkbox/stories.tsx
> +        action('checkbox clicked')(value, !checked);
a few extra goodies here

2021-05-28 15:07 UTC, caravinci commented on uikit/form/FormCheckbox/stories.tsx
> +      if (typeof value === 'string') {
though this is not really necessary for the correct functioning of the logic, I've added it in order to decrease the amount of noise displayed in the actions panel. It is only here to compensate for the bubbling issues mentioned before.

2021-05-28 15:07 UTC, caravinci commented on uikit/form/FormControl/FormControlContext.tsx
> +  handleBlur?: (e?: any) => any;
hinting (without enforcement) that the functions are supposed to expect an event, to prevent more usage of the `value` approach.

2021-05-28 15:34 UTC, joneubank requested changes
As discussed offline, need to refactor the double handler call.

2021-05-28 15:34 UTC, joneubank commented on uikit/form/Checkbox/index.tsx
> +    fn?.(value);
This will cause all checkbox event handlers to double trigger, which is a big change from how Checkbox previously functioned. We can't do this.

2021-05-28 15:47 UTC, caravinci commented
Agreed 100%. Changes coming right up.

2021-05-28 17:25 UTC, caravinci commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +    const value = event.target?.defaultValue;
takes the value from the event, rather than expecting it directly from the checkbox handler.

2021-05-30 21:14 UTC, caravinci commented
Rebased from develop

2021-05-31 13:38 UTC, ciaranschutte commented
@caravinci looks good to me after fixing the double trigger
requested @joneubank to review as I'm not sure the full discussion you two had regarding changes

2021-05-31 14:10 UTC, joneubank approved these changes
lookin good.

2021-05-31 14:12 UTC, merged