WIP: ✨ #2156 Facet Panel Tabs
icgc-argo/platform-ui pull request #2167
Opened 2022-01-19 21:24 UTC by demariadaniel

**Description of changes**

Implements Tabs for toggling between Clinical Filters and File Filters on the Facet Panel
Feature flagged

**Type of Change**

- [ ] Bug
- [ ] Styling
- [x] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [x] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [x] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [x] Feature is minimally responsive
- [x] Manual testing of UI feature
- [x] Add copyrights to new files
- [x] Connected ticket to PR

2022-01-20 17:00 UTC, samrichca commented on components/pages/file-repository/FacetPanel/index.tsx
> +    border-top: ${currentTab === tabValue ? `4px solid ${theme.colors.secondary}` : null};
I would use `0` instead of `null` here. I don't think `null` will break anything per se, but it's not a standard CSS value.

2022-01-20 17:02 UTC, samrichca commented on components/pages/file-repository/FacetPanel/index.tsx
> +              <Tab value="clinical" label="Clinical Filters" css={tabStyles('clinical')} />
the CSS prop here. nice!

2022-01-20 17:36 UTC, demariadaniel commented on components/pages/file-repository/FacetPanel/index.tsx
> +              <Tab value="clinical" label="Clinical Filters" css={tabStyles('clinical')} />
thanks i wasn't sure how this would be received as the rest of the app is largely using css inline ;)

2022-01-20 17:37 UTC, demariadaniel commented on components/pages/file-repository/FacetPanel/index.tsx
> +    border-top: ${currentTab === tabValue ? `4px solid ${theme.colors.secondary}` : null};
good point, maybe i can use 'initial' or 'inherit', i was trying to 'short circuit' here so there are no changes unless it's the active tab

2022-01-20 18:07 UTC, demariadaniel commented on components/pages/file-repository/FacetPanel/index.tsx
> +    border-top: ${currentTab === tabValue ? `4px solid ${theme.colors.secondary}` : null};
OK turns out the whole thing could be greatly simplified by just leveraging the `active` class, give it a 2nd look when you can. thanks!

2022-01-20 19:24 UTC, samrichca commented on components/pages/file-repository/FacetPanel/index.tsx
> +    border-top: ${currentTab === tabValue ? `4px solid ${theme.colors.secondary}` : null};
even better. ok, ship it!

2022-01-20 19:24 UTC, samrichca approved these changes

2022-01-20 20:48 UTC, mistryrn requested changes
Looks good! We should probably also add this feature flag to the `.env.schema` as well. Once I added the flag to my .env it worked like a charm!

I'm not sure the exact process to add this flag to dev/qa/prod, I think it has something to do with helm charts. Someone like Henro would likely be able to point you in the right direction there.

2022-01-21 18:59 UTC, demariadaniel commented
> Looks good! We should probably also add this feature flag to the `.env.schema` as well. Once I added the flag to my .env it worked like a charm!
> 
> I'm not sure the exact process to add this flag to dev/qa/prod, I think it has something to do with helm charts. Someone like Henro would likely be able to point you in the right direction there.

Added to `env.schema`
PR for infra dev here: https://github.com/OICR/argo-infra/pull/694

2022-01-21 19:00 UTC, mistryrn approved these changes
🚀

2022-01-21 19:10 UTC, merged