🐛 #1794 Update Profile Token Generation Logic
icgc-argo/platform-ui pull request #2193
Opened 2022-02-03 21:11 UTC by demariadaniel

**Description of changes**

Checks JWT for Scopes to determine whether user can generate a token

**Type of Change**

- [x] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [x] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [x] Feature is minimally responsive
- [x] Manual testing of UI feature
- [x] Add copyrights to new files
- [x] Connected ticket to PR

2022-02-03 21:17 UTC, joneubank requested changes

2022-02-03 21:17 UTC, joneubank commented on components/pages/user/index.tsx
> +  const hasTokenAccess = scope && scope.length > 0;
unfortunately, Ego's hack for empty scopes is a JWT with scope = {*.DENY} so this would return true...

Can we check for something equivalent to "has at least one entry with READ or WRITE permission"?

There are methods in the `egoTokenUtils` that can return the individual scopes of the JWT (or you can parse this yourself).

2022-02-04 15:20 UTC, demariadaniel commented on components/pages/user/index.tsx
> +  const hasTokenAccess = scope && scope.length > 0;
OK I've updated this to check for Read / Write scopes
& I've also removed checks for Daco approval for token generation
Take a second look when you get a chance, thanks!

2022-02-04 15:25 UTC, joneubank commented on components/pages/user/index.tsx
> +  const hasTokenAccess = scope && scope.some((element) => element.match(/.READ|.WRITE/gm));
Nice use of regex. I think we shouldn't have global or multiline flags, instead confirm that one of these ends the line (though this is nitpicking cause in theory they always will).

Something like `/(\.READ|\.WRITE)$/`

2022-02-04 15:26 UTC, joneubank commented on components/pages/user/index.tsx
> +  const hasTokenAccess = scope && scope.some((element) => element.match(/.READ|.WRITE/gm));
(also `.` checks any character, so we do at least need that escaped like `\.` to not match a policy with READ or WRITE in it)

2022-02-04 16:15 UTC, demariadaniel commented on components/pages/user/index.tsx
> +  const hasTokenAccess = scope && scope.some((element) => element.match(/.READ|.WRITE/gm));
Yep all good points, updated!

2022-02-04 19:53 UTC, joneubank approved these changes
Beauty. Thank you sir.

2022-02-04 20:04 UTC, merged