✨ Enable `Small File Downloads` (#2091)
icgc-argo/platform-ui pull request #2243
Opened 2022-03-15 13:23 UTC by mistryrn

**Description of changes**

* Add File download button back to File Entity page
* Connect to new `/get-download-url` endpoint of File Storage API

**Type of Change**

- [ ] Bug
- [ ] Styling
- [x] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [x] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [x] No new UIKit components or changes
- [x] Feature is minimally responsive
- [x] Manual testing of UI feature
- [x] Add copyrights to new files
- [x] Connected ticket to PR

2022-03-15 15:26 UTC, demariadaniel commented
tested locally, disabled states are working fine
tooltip may need to be updated for users w/o daco-approval
api is not merged so download is not working yet

2022-03-15 15:27 UTC, demariadaniel requested changes
tested locally, disabled states are working fine
tooltip may need to be updated for users w/o daco-approval
api is not merged so download is not working yet

2022-03-17 15:09 UTC, joneubank commented on components/pages/file-repository/utils/constants.tsx
> +export const MAX_FILE_DOWNLOAD_SIZE = 100000000; // 100MB
Should we make this a configurable value?

2022-03-17 18:18 UTC, mistryrn commented on components/pages/file-repository/utils/constants.tsx
> +export const MAX_FILE_DOWNLOAD_SIZE = 100000000; // 100MB
Good idea, I'll update it here and in the API to be configurable via env var

2022-04-04 14:09 UTC, mistryrn commented on global/utils/stringUtils.ts
> +  const filenameRegex = /(?<=filename(?:=|\*=(?:[\w\-]+'')))["']?([^"';\n]+)["']?/gi;
Regex demo here: https://regex101.com/r/FkLhkr/1

Grabs whatever follows the `filename=` in the `Content-Disposition: attachment; filename="filename.txt"` header, handles a few special cases that might occur.

2022-04-04 14:35 UTC, ciaranschutte commented on global/utils/stringUtils.ts
> +  const filenameRegex = /(?<=filename(?:=|\*=(?:[\w\-]+'')))["']?([^"';\n]+)["']?/gi;
sick! that's for the demo

2022-04-04 21:13 UTC, demariadaniel approved these changes

2022-04-04 21:38 UTC, merged