WIP: Feat/539 fetch all clinical data
icgc-argo/platform-ui pull request #2284
Opened 2022-04-13 20:07 UTC by demariadaniel

**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] New Components with storybook stories created
  - [ ] Modified Existing components and updates stories
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

2022-05-10 20:10 UTC, samrichca commented on components/pages/submission-system/SideMenu.tsx
> +  entityFields: Array<[]>;
Is it possible to define a type for `<[]>`?

2022-05-10 20:33 UTC, demariadaniel commented on components/pages/submission-system/SideMenu.tsx
> +  entityFields: Array<[]>;
For now I can definitely update to String[] for sure, if we want to be more specific, on the Service side this is a massive Union Type:
https://github.com/icgc-argo/argo-clinical/blob/49512149a92cef58a7cbe5535047a98cec895cf7/src/common-model/entities.ts#L42

Ideally we'd have a similar definition on the front end, could potentially just copy the whole `common-model/entities` file somewhere appropriate in UI

2022-05-11 14:12 UTC, samrichca commented on components/pages/submission-system/SideMenu.tsx
> +  entityFields: Array<[]>;
It looks like we don't copy over types in that much detail for other features. String[] is right on the money.

2022-05-18 15:17 UTC, joneubank requested changes
Functionality looks good, just suggesting improvements for lighter data fetching and for code organization.

2022-05-18 15:17 UTC, joneubank commented on components/pages/submission-system/SideMenu.tsx
> +}
a lot of these types look like they're here to help describe the results of the fetch all data... from a code organization perspective it seems strange that this would be in a component called SideMenu.

Is there a way to move the api fetch and data structuring into a file dedicated for api fetching?

2022-05-18 15:17 UTC, joneubank commented on components/pages/submission-system/SideMenu.tsx
> +    });
For the sidemenu, we don't need the entirety of the clinical data... is there a smaller query that gets us just the data we need so we don't have to build a heavy query into our menu?

Maybe it just fetches `ClinicalErrorData` , or maybe we can even add a new resolver into the gql scheme that checks for "has errors" as a boolean.

2022-05-18 15:19 UTC, demariadaniel commented on components/pages/submission-system/SideMenu.tsx
> +}
@joneubank this is done in: https://github.com/icgc-argo/platform-ui/pull/2300/  :)

2022-05-18 15:21 UTC, joneubank commented on components/pages/submission-system/SideMenu.tsx
> +}
I see it now, thanks.

2022-05-18 16:14 UTC, demariadaniel commented on components/pages/submission-system/SideMenu.tsx
> +    });
Will update as a separate ticket or as part of https://github.com/icgc-argo/platform-ui/pull/2304

2022-05-18 16:14 UTC, merged