⬆️ #2299 - Upgrade dependencies
icgc-argo/platform-ui pull request #2305
Opened 2022-05-17 21:39 UTC by samrichca

# Description of changes

## Type of Change

- [ ] Bug
- [ ] Styling
- [ ] New Feature

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] Modified Existing components
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

2022-06-02 19:52 UTC, ciaranschutte commented
@samrichca can we leave out the uikit changes please? I'm trying to get that one wrapped today. It's taking a long time because there's been additions here that were not synced. So this will just add more to it.

2022-06-08 15:18 UTC, samrichca commented
Looked over `resolutions` in package.json and I'll have to revisit them when I get to the Babel ticket at the end. Made a note of that in my spreadsheet.

2022-06-14 16:09 UTC, ciaranschutte commented
noticed `husky 4` is a significant update.
worth upgrading to the latest 8 if we're upgrading at all? https://github.com/typicode/husky @samrichca

2022-06-14 18:12 UTC, samrichca commented
@ciaranschutte I actually did the Husky 4 upgrade because I couldn't commit to this branch without it. I'm planning on doing a Husky 8 and Prettier upgrade and running Prettier on the codebase on that PR. Does that work?

2022-06-14 18:13 UTC, ciaranschutte commented
> @ciaranschutte I actually did the Husky 4 upgrade because I couldn't commit to this branch without it. I'm planning on doing a Husky 8 and Prettier upgrade and running Prettier on the codebase on that PR. Does that work?

sounds good

2022-06-14 20:15 UTC, ciaranschutte requested changes

2022-06-14 20:15 UTC, ciaranschutte commented on package.json
> +    "local-build": "rm -rf .next && next build",
same as `build` command? @samrichca

2022-06-14 20:16 UTC, ciaranschutte commented on package.json
> +    "local-build": "npm run build-uikit && rm -rf .next && next build",
^outdated

2022-06-14 20:17 UTC, samrichca commented on package.json
> +    "local-build": "rm -rf .next && next build",
Doh, good catch. Added this when uikit was giving me trouble.

2022-06-14 20:19 UTC, samrichca commented on package.json
> +    "local-build": "rm -rf .next && next build",
Removed

2022-06-14 20:20 UTC, ciaranschutte approved these changes

2022-06-14 20:25 UTC, merged