🧪 2296 Submitted Data Table
icgc-argo/platform-ui pull request #2313
Opened 2022-05-26 17:16 UTC by demariadaniel

# Description of changes

## Type of Change

- [ ] Bug
- [ ] Styling
- [ ] New Feature

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- UI Kit (select one):
  - [ ] Modified Existing components
  - [ ] No new UIKit components or changes
- [ ] Feature is minimally responsive
- [ ] Manual testing of UI feature
- [ ] Add copyrights to new files
- [ ] Connected ticket to PR

2022-05-30 14:59 UTC, ciaranschutte reviewed
looks great. pagination logic is nice and clean.

2022-05-30 14:59 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/index.tsx
> +              <DataTable entityType={selectedClinicalEntityTab} program={programShortName} />
type error
`DataTable` is expecting program to be a single `string`
`programShortName` type is `string | string[]`

2022-05-30 14:59 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/common.tsx
> +    programShortName?: string;
just checking `programShortName` is optional?

2022-05-30 15:00 UTC, ciaranschutte requested changes
build fix please :) (I hit comment instead of request ch-ch-chaaanges)

2022-05-30 19:00 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/common.tsx
> +    programShortName?: string;
Yeah because it's required in the query filters, you're requesting data by program.
So it's not required in the response because you already have it in the request. So you can take it out of the GQL query if you wanted (just need programName in the variables);

This is also a workaround so we can keep `emptyResponse` a simple (but typed) object with no program name, rather having to make it a function which takes a programName as an argument.

Lmk if you'd do it differently

2022-05-30 19:08 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/common.tsx
> +    programShortName?: string;
lgtm!

2022-05-30 19:37 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/index.tsx
> +              <DataTable entityType={selectedClinicalEntityTab} program={programShortName} />
I'll update this to get programShortName through the route, should fix this

2022-05-30 21:11 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/index.tsx
> +              <DataTable entityType={selectedClinicalEntityTab} program={programShortName} />
Updated -- using `as string` fixes the build issues
Jenkins is failing b/c API changes need to merged first

2022-05-31 19:55 UTC, demariadaniel commented
> build fix please :) (I hit comment instead of request ch-ch-chaaanges)

pipeline's fixed + changes addressed!

2022-05-31 20:08 UTC, ciaranschutte approved these changes

2022-05-31 20:09 UTC, merged