Feat/new/2270 submitted data make the filter by id list modal work
icgc-argo/platform-ui pull request #2435
Opened 2022-11-04 13:13 UTC by daniel-cy-lu

# Description of changes

## Type of Change

- [ ] Bug
- [ ] Dependency updates
- [ ] Feature
- [ ] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [ ] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [ ] Manually tested changes
- [ ] Added copyrights to new files
- [ ] Connected ticket to PR

2022-11-04 19:27 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +  console.log('filterTextBox', filterTextBox);
Forgot to remove a console.log here

2022-11-04 19:29 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +          ></Textarea>
This could just be a self-closing tag correct? `<Textarea {...props} />` vs `<Textarea {...props}></Textarea>`

2022-11-04 19:38 UTC, demariadaniel commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +    if (filterTextBox) {
You could probably move this condition up to the top of `useEffect` so that you only do all the relevant processing if filterTextBox is truthy

example:
```
useEffect(() => {
  if (filterTextBox) {
    {... lines 87  to 114 }
   } else {
     setNumMatched(0);
      setNumUnmatched(0);
      }
      }, [searchResultData]);
```

2022-11-07 15:43 UTC, ciaranschutte commented
taking a look at this

2022-11-07 17:18 UTC, daniel-cy-lu commented
Thank you Dan and Ciaran for spending time on this pr review! :D

2022-11-07 20:23 UTC, ciaranschutte requested changes
This looks really good! Love your comments and the usage of `Set`. it's easy to follow and well structured. i have a few recommendations

2022-11-07 20:23 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +        filteredTextAreaIDs.delete(result.submitterDonorId);
these two conditionals work better as if/else because you're not returning assigning anything

2022-11-07 20:23 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +      .match(/(^\d)\d*|((?<=,)|(?<=DO))\d*/gi)
i think this regex is used a couple of times. might be worth putting it somewhere once, so it's easier to maintain.
i'm guessing the filter is to rule out empty strings?

2022-11-07 21:06 UTC, ciaranschutte commented
I think we should only change state on pressing "View results".
Otherwise it's unclear to a user how the state is actually changing.
eg. is cancel button cancelling my filter? no it's just for the modal

This creates the problem of needing a clear button for the input.
I have posted about this in argo dev slack channel to hear what the team has to say

2022-11-10 16:23 UTC, daniel-cy-lu commented
> I think we should only change state on pressing "View results". Otherwise it's unclear to a user how the state is actually changing. eg. is cancel button cancelling my filter? no it's just for the modal
> 
> This creates the problem of needing a clear button for the input. I have posted about this in argo dev slack channel to hear what the team has to say

I feel that there is 'some touch' up to do with this View Result button as well. For instance, reopening the filter modal will not clear the text field. And 'Clinical Data for:' is not updating.

2022-11-10 19:41 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/index.tsx
> +  }
this is looking great. I was thinking of pushing this even slightly further...I'm having some trouble with the VPN so I haven't tested this yet. Here is some rough code. So all the actually uploading can be moved to UploadButton. The only part this file has to worry about is what to do with the results.

So it'll look like:
``` javascript
<UploadButton onClick={(results) => {
              if (filterTextBox) {
                setFilterTextBox(filterTextBox + ', ' + results);
              } else {
                setFilterTextBox(results);
              }}/>
```

2022-11-10 19:42 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/UploadButton.tsx
> +}
then we'll add most of the upload functionality here. and clean up some duplicated code in the process.
``` javascript
import React from 'react';
import { Button } from '@icgc-argo/uikit/';
import { fileOpen, supported } from 'browser-fs-access';

const formatResult = (texts) => {
  return texts.join().replace(/\s/g, '').replace(/,/g, ', ');
};

export default function UploadButton({ onUpload }: { onUpload: any }) {
  const upload = async () => {
    let fileHandle;

    // Refer to File System Access API. Restrict conditions when doing file uploads
    const ifSupportedPickerOpts = {
      types: [
        {
          accept: {
            'text/*': ['.txt', '.csv', '.tsv'],
          },
        },
      ],
      excludeAcceptAllOption: true,
      multiple: true,
    };

    //upload button will use showOpenFilePicker (file system access API )method when supported by browser ie. Chrome and Edge, then fall back to legacy method if unsupported ie. FireFox.

    if (supported) {
      try {
        fileHandle = await window.showOpenFilePicker(ifSupportedPickerOpts);
        const files = await Promise.all(fileHandle.map(async (file) => await file.getFile()));
        const texts = await Promise.all(files.map(async (text) => await text.text()));
        // format results so each id has ', ' in between
        const results = formatResult(texts);
        onUpload(results);
      } catch (err) {
        return;
      }
    } else {
      //if browser doesn't support File System Access API, then use legacy method
      const unsupportedFiles = await fileOpen([
        {
          description: 'Text files',
          mimeTypes: ['text/*'],
          extensions: ['.txt', '.csv', '.tsv'],
          multiple: true,
        },
      ]);

      const unsupportedText = await Promise.all(
        unsupportedFiles.map((file) => {
          return file.text();
        }),
      );
      // format results so each id has ', ' in between
      const results = formatResult(unsupportedText);
      onUpload(results);
    }
  };

  return (
    <Button size="sm" onClick={upload}>
      Browse
    </Button>
  );
}

```

2022-11-10 19:43 UTC, ciaranschutte commented on components/pages/submission-system/program-submitted-data/SearchBar/FilterModal/UploadButton.tsx
> +}
so this component becomes fully responsible for just uploading the file... but we can modify what we do with the upload by passing in our onClick function.

2022-11-10 21:30 UTC, ciaranschutte approved these changes

2022-11-10 21:32 UTC, merged