#2474 feature request add number tooltip to molecular and core clinical chart
icgc-argo/platform-ui pull request #2552
Opened 2023-01-18 21:20 UTC by daniel-cy-lu

# Description of changes

Add a tooltip to the Clinical and Molecular Chart. The tooltip as well as a vertical black line are displayed when the mouse is hovered over an area on the chart. The vertical line is lines up to the current x-coordinate. The tooltip has an arrow that points to the vertical line so user can clearly see which x-coordinate the mouse is currently hovered over. The tooltip displays information under the DNA and RNA titles. There are coloured circles in front of the text/count inside the tooltip box that match with the lines on the chart. The tooltip will flip to the side with more space so content will not get hidden.

## Type of Change

- [ ] Bug
- [ ] Dependency updates
- [ ] Feature
- [ ] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [ ] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [ ] Manually tested changes
- [ ] Added copyrights to new files
- [ ] Connected tick

<img width="338" alt="Screenshot 2023-01-18 at 4 05 41 PM" src="https://user-images.githubusercontent.com/79996555/213297028-f7be241d-e52f-45eb-a7c4-c408abdbc2e6.png">
<img width="337" alt="Screenshot 2023-01-18 at 4 05 30 PM" src="https://user-images.githubusercontent.com/79996555/213297029-8beabe27-586d-4bea-8207-3dd665bfad6a.png">
<img width="336" alt="Screenshot 2023-01-18 at 4 05 19 PM" src="https://user-images.githubusercontent.com/79996555/213297030-0c8c2c5b-286a-4501-9b47-73d1da8ada33.png">
<img width="339" alt="Screenshot 2023-01-18 at 4 05 08 PM" src="https://user-images.githubusercontent.com/79996555/213297033-e9b8b5a6-a34d-42a4-b4c3-9deecad319dc.png">
et to PR

2023-01-18 21:22 UTC, daniel-cy-lu commented
Thanks Sam for all your brain power! There is so much math and reduce method involved in this ticket! @samrichca

2023-01-18 21:28 UTC, samrichca commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +                <tspan x={xText} y={yText + idx * lineHeight} fontWeight="bold">
I would change this to add a new constant like `isHeader` to make this clearer.

```
{tooltipList.map((tooltipItem, idx) => {
  const isHeader = !tooltipItem.color;
  return (
```

and then further down

```
{isHeader
? <tspan bold>{name}</tspan>
: <tspan>{name}</tspan>
}
```

2023-01-18 21:31 UTC, samrichca commented on components/pages/submission-system/program-dashboard/index.tsx
> +      {/* {
remove comments :)

2023-01-18 21:41 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +                <tspan x={xText} y={yText + idx * lineHeight} fontWeight="bold">
making things clear! This is better than my comments. I will remove those. I also used `!isHeader` for the text portion.

2023-01-18 21:41 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/index.tsx
> +      {/* {
oops!

2023-01-18 21:46 UTC, samrichca commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    // arrow pointer
nice 💯

2023-01-18 22:13 UTC, joneubank commented
Just judging from the provided screenshots... when there is only 1 data series, can we remove the label and make the value vertically centered?

2023-01-18 22:17 UTC, daniel-cy-lu commented
@joneubank Will work on that! Can't directly reply to your message.

2023-01-19 17:13 UTC, joneubank commented
@daniel-cy-lu much better overall. Is the width fixed? would be nice if it reduced in this case with so little text.

2023-01-19 17:20 UTC, daniel-cy-lu commented
@joneubank sorry when you said vertically centered earlier, I thought you only want the changes to happened vertically
<img width="339" alt="Screenshot 2023-01-19 at 12 18 22 PM" src="https://user-images.githubusercontent.com/79996555/213515340-143bfbbe-eb99-423a-9e30-5d814f8d874d.png">

How is this?

2023-01-20 15:18 UTC, daniel-cy-lu commented
Merge Conflict resolved. Manual tested. Everything looks good! @samrichca
<img width="333" alt="Screenshot 2023-01-20 at 10 14 57 AM" src="https://user-images.githubusercontent.com/79996555/213733843-8a694665-d069-436f-ab74-08721ef81d11.png">
<img width="335" alt="Screenshot 2023-01-20 at 10 14 47 AM" src="https://user-images.githubusercontent.com/79996555/213733847-0d8b6f13-48f8-422b-b935-01d9a4018c71.png">

2023-01-20 15:40 UTC, daniel-cy-lu commented
Added back condition to make tooltip width shorter to fit if there is only one item.
<img width="335" alt="Screenshot 2023-01-20 at 10 34 19 AM" src="https://user-images.githubusercontent.com/79996555/213741232-899a206f-7d86-4d76-8f6c-10e61f2b27ed.png">

2023-01-25 15:21 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    const boxWidth = isOneItem ? 56 : width;
When there is only one item we lose the ability to define the width. Why not just let the user define the width or use the default?

2023-01-25 17:13 UTC, joneubank requested changes
Functionally this all looks great. I would like to do a bit of refactoring to separate the new InfoBox component from being hardcoded into the LineChart. While we don't have places where we want to reuse this right now, its good to build our components with modularity in mind. I put some direct comments about those changes in the review. Thanks Daniel!

2023-01-25 17:13 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +  const InfoBox = ({ width }: { width?: number }) => {
Can we refactor this to have `InfoBox` be a separate component in its own file and imported into this one. Separating components into standalone pieces will help with future reusability, and forces us to consider hte interfaces of the components.

For example, to move this component out of this file, we will have to pass many values as props to the info box that right now are being read from the LineChart scope. I think it is good to know the various properties that this InfoBox relies on. For example, we should pass the `xStart`, `yStart` and `xIsLeft` as props, like we do `width`.

2023-01-25 17:13 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/index.tsx
> +                tooltipData={tooltipData}
This data does not need to be passed in as a prop. The `data` prop has all the required information, and it can be transformed into `tooltipData` inside the LineChart. This stops us from passing in duplicate data, but more importantly it allows  the LineChart to be used int he future without requiring the developer using it to know how to generate tooltipData.

2023-01-25 19:54 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    const boxWidth = isOneItem ? 56 : width;
<img width="337" alt="Screenshot 2023-01-25 at 2 48 42 PM" src="https://user-images.githubusercontent.com/79996555/214673646-6c56a139-3a72-47da-b7c2-077d1c62bdbd.png">
That's a good point Jon. If you see the screenshot, because for one-item-charts, we removed the text, now there is a lot of empty space. So Sam and I made it this way. I think or maybe we could add an one-item-width prop and have it default to 56? Is this a good way if we don't want so much empty space like in the screenshot? @samrichca

2023-01-25 19:55 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +          {toolTipIndex !== null && <InfoBox width={infoBoxWidth} />}
I removed the duplicate. The one inside the InfoBox return line has been removed.

2023-01-25 19:57 UTC, samrichca commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    const boxWidth = isOneItem ? 56 : width;
we could have defaults for one item & multi-item, that can be overridden by the user

2023-01-25 20:57 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    const boxWidth = isOneItem ? 56 : width;
that is also acceptable, just so long as the user has the ability to override either.

2023-01-27 19:20 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +    const boxWidth = isOneItem ? 56 : width;
**Solution:** add a new prop to `LineChart` that is passed to `InfoBox`. The prop, onItemBoxWidth has a default value 56. Together with infoBoxWidth, these two props allow user to override tooltip width or use the default values. Screenshot of default look: 
![Screenshot 2023-01-27 at 2 18 57 PM](https://user-images.githubusercontent.com/79996555/215178161-8236ea6b-a167-4cbf-8a8d-666a6241a5ff.png)

2023-01-27 20:01 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +  const InfoBox = ({ width }: { width?: number }) => {
InfoBox is now its own component in a separate file. I also moved xStart and xIsLeft declaration to the LineChart level. (these two values are now props of InfoBox). Having some difficulty moving yStart because of tooltipList's scope. Will see if it's resolved when solving the next comment change.

![Screenshot 2023-01-27 at 2 59 03 PM](https://user-images.githubusercontent.com/79996555/215186155-2c2893de-10de-40f6-b5d7-4e3bcc4af6bb.png)

2023-01-27 20:43 UTC, quantropi-minh commented
I wish I could log in and see these awesome charts in action T_T

2023-01-27 20:49 UTC, daniel-cy-lu commented
@quantropi-minh Not just charts, tooltips! :D

2023-01-31 14:24 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/index.tsx
> +                tooltipData={tooltipData}
Got @samrichca help to reduce redundancy. tooltipData is now moved from `ClinicalChart` into `InfoBox` along with some variables in the `utils`.

2023-01-31 16:59 UTC, joneubank requested changes
Really small requests this time, looks great.

One additional change request in addition to the other comments: Can you go throw the code and standardize if you are using `ToolTip` or `Tooltip`.

2023-01-31 16:59 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/InfoBox.tsx
> +  const tooltipList = tooltipData[toolTipIndex];
This seems strange that we are passing in more data than the info box needs then using a utility method to transform it. Couldn't we just provide the data in the props as `TooltipData` type, then we don't need to pass in the `toolTipIndex` as well?

2023-01-31 16:59 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/InfoBox.tsx
> +  oneItemBoxWidth,
Let's standardize the naming here:
```
multiItemWidth,
singleItemWidth,
```

2023-01-31 16:59 UTC, joneubank commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +          )}
👍

2023-01-31 18:39 UTC, daniel-cy-lu commented
> Really small requests this time, looks great.
> 
> One additional change request in addition to the other comments: Can you go throw the code and standardize if you are using `ToolTip` or `Tooltip`.

tooltip should be one word. Changed all variables with `toolTip` and `ToolTip` to `tooltip`.

2023-01-31 18:40 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/index.tsx
> +          )}
thanks Jon!

2023-01-31 18:58 UTC, daniel-cy-lu commented on components/pages/submission-system/program-dashboard/ClinicalChart/LineChart/InfoBox.tsx
> +  const tooltipList = tooltipData[toolTipIndex];
Oh my bad, I should have move tooltipData from ClinicalChart into LineChart. And I've corrected it. so tooltipList is now a prop and tooltipIndex is removed as a prop.

2023-02-09 16:39 UTC, joneubank approved these changes
Awesome!

2023-02-09 17:46 UTC, merged