#2526 Build a Static Program Entity Page
icgc-argo/platform-ui pull request #2570
Opened 2023-02-10 21:02 UTC by daniel-cy-lu

# Description of changes

Create a Program Entity Page UI, with a directory of `root/program`. The design is consistent with the rest of the page.

## Type of Change

- [ ] Bug
- [ ] Dependency updates
- [ ] Feature
- [ ] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [ ] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [ ] Manually tested changes
- [ ] Added copyrights to new files
- [ ] Connected ticket to PR

Screenshot of Regular View
<img width="1434" alt="Screenshot 2023-02-10 at 3 59 08 PM" src="https://user-images.githubusercontent.com/79996555/218196614-86dca6b9-a5ae-4bec-a59e-73748240911d.png">

Screenshot of Shrunk Width:
<img width="849" alt="Screenshot 2023-02-10 at 3 59 36 PM" src="https://user-images.githubusercontent.com/79996555/218196447-329b4dfc-d74e-4510-a294-3b2caea6e4e0.png">

2023-02-10 21:07 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
For the circleFill, iconFill props, I tried assigning `ThemeColorNames` which are the type of `fill` prop of `CircleContainer` and `Icon`. It didn't work. Would someone know the reason why?

2023-02-10 21:08 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> +export default ProgramDonorAndFileCountsTable;
This Component produces the two tables at the bottom of the page. We are using table with title.

2023-02-10 21:10 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +export default ProgramSummaryLink;
The links are hidden for this UI ticket. I call them link. This Component produces the three icons and their corresponding links at the top right part of the page.

2023-02-10 21:11 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/index.tsx
> +export default ProgramSummaryLinkContainer;
This Component is the container of the icon link at the top right part of the page.

2023-02-10 21:13 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryTable/index.tsx
> +export default ProgramSummaryTable;
This Component is the table at the upper part of the page. It is using a simple table because titles are not required.

2023-02-10 21:14 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/index.tsx
> +export default ProgramCardsLayout;
This Component is the container of body of the page. It holds the three major parts of the body of the page.

2023-02-13 16:16 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
Thanks for the comment, Dan. Let me take a look!

2023-02-13 16:37 UTC, samrichca commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
those other components are using `keyof ThemeColorNames` which creates a string literal type, i.e. `success | warning | error | grey ...`

2023-02-13 16:44 UTC, samrichca commented on pages/program/index.tsx
> +import Program from 'components/pages/program';
this should be changed to `import ProgramEntity from 'components/pages/ProgramEntity'` for consistency with donor & file entities

2023-02-13 16:44 UTC, samrichca commented on pages/program/index.tsx
> +  return <Program />;
change to `<ProgramEntity />`

2023-02-13 16:44 UTC, daniel-cy-lu commented
@samrichca spelling mistake on `Strategies` updated.

2023-02-13 16:48 UTC, samrichca commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
I didn't see Dan's comment because I had this tab open for a long time. good idea @demariadaniel

2023-02-13 16:50 UTC, daniel-cy-lu commented on pages/program/index.tsx
> +  return <Program />;
edit files, and component name to program-entity and `ProgramEntity`

2023-02-13 16:51 UTC, samrichca commented on components/pages/program/ProgramCardsLayout/index.tsx
> +    { Stragegies: 'WXS', Donors: 245, Files: 245 },
strategies spelling again ;)

also please leave a comment indicating these are mock data

2023-02-13 16:58 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/index.tsx
> +    { Stragegies: 'WXS', Donors: 245, Files: 245 },
It's good now after refreshing the page. I think it was still showing the wrong spelling because I just updated the file name.

2023-02-13 17:00 UTC, samrichca commented
looks good now, thanks for the quick changes 💯

2023-02-13 17:01 UTC, samrichca commented on components/pages/program-entity/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
change to `keyof ThemeColorNames`

we should add a proper type to uikit, but keyof is OK for now

2023-02-13 17:11 UTC, daniel-cy-lu commented on components/pages/program/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
I updated `circleFill` and `iconFill's` type to` keyof ThemeColorNames` and they stopped screaming!
<img width="490" alt="Screenshot 2023-02-13 at 12 09 22 PM" src="https://user-images.githubusercontent.com/79996555/218525179-0b24cec2-e670-41bb-9354-0e97a79877d3.png">

2023-02-13 17:12 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/ProgramSummaryLinkContatiner/ProgramSummaryLink.tsx
> +  circleFill: any;
updated the type!
<img width="490" alt="Screenshot 2023-02-13 at 12 09 22 PM" src="https://user-images.githubusercontent.com/79996555/218525539-36dac609-da16-4c9a-8023-e8c80d2255bf.png">

2023-02-13 18:01 UTC, ciaranschutte commented on components/pages/program-entity/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
2023?

2023-02-13 18:02 UTC, ciaranschutte commented
2023 for all copyright. i thnk @samrichca had a script?

2023-02-13 18:02 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
oh why didn't I thought of that!? :)

2023-02-13 18:03 UTC, ciaranschutte commented on components/pages/program-entity/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
copy / paste .... I only caught it because I was pasting 2022 30mins ago ;p

2023-02-13 18:06 UTC, ciaranschutte commented on components/pages/program-entity/index.tsx
> +  const loading = false;
`loading` isn't doing anything so isn't needed. similarly down when you use it as a conditional can just be shortened as `loading` will always be false, so <DnaLoader> is never going to render

2023-02-13 18:06 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
I changed the year, waiting for Sam if she has a new script!

2023-02-13 18:07 UTC, ciaranschutte commented on components/pages/program-entity/ProgramCardsLayout/ProgramDonorAndFileCountsTable/index.tsx
> + * Copyright (c) 2022 The Ontario Institute for Cancer Research. All rights reserved
it's only a couple of files.. I may have gotten over zealous about copyright script use case :p

2023-02-13 18:14 UTC, daniel-cy-lu commented on components/pages/program-entity/index.tsx
> +  const loading = false;
I think I left it there to remind whoever that is working on the API that there is a loading here. I got the idea from other pages like donor-entity and file-entity. I should and will leave a comment here for its purpose.

2023-02-13 18:37 UTC, ciaranschutte commented on components/pages/program-entity/index.tsx
> +  const loading = false;
Good future thinking!

Those pages are currently "doing stuff" that has a loading state.
There may not be any loading at all on this page ever, or loading may be constrained to child components, then there's unreachable code with extra data of an unused component. (chances are there will be, trying to illustrate overall not to add unneeded code)

It's the responsibility of the developer who implements the improvements to this page to add it :)

2023-02-13 18:42 UTC, daniel-cy-lu commented on components/pages/program-entity/index.tsx
> +  const loading = false;
AHH! I got the point! Thank Ciaran, I will remove `loading`. It's not needed at the moment, so we shouldn't leave it in the codes. If it's needed, it could be added later on. (Y)

2023-02-13 18:43 UTC, ciaranschutte commented on components/pages/program-entity/index.tsx
> +  const loading = false;
thanks @daniel-cy-lu !

2023-02-13 19:48 UTC, samrichca commented
"2023 for all copyright please. i thnk @samrichca had a script?" @ciaranschutte I had one for adding copyright to files without it i.e. in a new repo, but in this case search & replace will do

2023-02-13 19:50 UTC, ciaranschutte commented
> "2023 for all copyright please. i thnk @samrichca had a script?" @ciaranschutte I had one for adding copyright to files without it i.e. in a new repo, but in this case search & replace will do

for sure

2023-02-13 20:02 UTC, ciaranschutte commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +  ];
let's put all this mock data into a separate file and import it.
easier to refactor it later.

when it comes time to remove it, we can just delete the import and have a file full of type errors instead of potential mock data spread throughout a component doing lots of work.

2023-02-13 20:02 UTC, ciaranschutte requested changes
https://github.com/icgc-argo/platform-ui/pull/2570/files#r1104961127

2023-02-13 20:49 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +  ];
Add these three variables containing mock data to a separate file, util.tsx.

2023-02-13 21:24 UTC, ciaranschutte commented
final comment from me is the DNALoader import can be removed, because its not in use anymore

2023-02-13 21:25 UTC, ciaranschutte commented
on mac "shift + option + o" will cleanup and removed unused imports for you.
I usually use that hotkey after I work on a file to make sure I'm not still importing things :)

2023-02-13 21:26 UTC, ciaranschutte commented
i checked out the page locally and it's looking great

2023-02-13 21:31 UTC, daniel-cy-lu commented
> on mac "shift + option + o" will cleanup and removed unused imports for you. I usually use that hotkey after I work on a file to make sure I'm not still importing things :)

WOW super useful hot key, Ciaran!! I cleaned up all the pages I worked on in this ticket!

2023-02-13 21:32 UTC, ciaranschutte approved these changes

2023-02-13 21:37 UTC, merged