Feat/2611 program entity page query arranger for donor counts
icgc-argo/platform-ui pull request #2667
Opened 2023-05-16 14:04 UTC by daniel-cy-lu

# Description of changes

Made a new query to request donor and file counts of 8 fields. 5 from Data Category and 3 from Experimental Strategy. These data are put into two tables at the lower portion of the Program Entity Page. 

## Type of Change

- [ ] Bug
- [ ] Dependency updates
- [ ] Feature
- [ ] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [ ] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [ ] Manually tested changes
- [ ] Added copyrights to new files
- [ ] Connected ticket to PR

##Screenshot
- With two programs, TEST-PR and TCRB-CA, I was able to test the query results in UI for all but **Transciptome Profiling**, which doesn't have an associated program.
<img width="1325" alt="Screenshot 2023-05-16 at 9 58 45 AM" src="https://github.com/icgc-argo/platform-ui/assets/79996555/fa26efab-46ae-4296-8c58-ba8a55e22ddd">
<img width="1326" alt="Screenshot 2023-05-16 at 9 58 20 AM" src="https://github.com/icgc-argo/platform-ui/assets/79996555/9c3c333f-4028-4800-91b2-20300e5a4ea4">
---
- Playground variable and result to compared to UI
![Screenshot 2023-05-16 at 9 54 42 AM](https://github.com/icgc-argo/platform-ui/assets/79996555/999ef4cf-b085-4005-9218-c1cc50a20b48)
![Screenshot 2023-05-16 at 9 54 00 AM](https://github.com/icgc-argo/platform-ui/assets/79996555/6954c9ad-6aa4-4447-a179-f4c22e1e50bc)

2023-05-16 14:19 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +
Same thing here. I would like to move these two const, but would need to be able to access the variable, `file` in the new file.

2023-05-16 14:20 UTC, daniel-cy-lu commented on components/pages/program-entity/gql/PROGRAM_SUMMARY_LINK_QUERY.ts
> +export default PROGRAM_SUMMARY_LINK_QUERY;
This is from the previous ticket #2617

2023-05-16 14:21 UTC, daniel-cy-lu commented on components/pages/program-entity/index.tsx
>          </PageContent>
This is from previous ticket #2617

2023-05-17 15:02 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> -  };
`programSummaryData` could be generated by a function, `createProgramSummaryData`, which is in `ult`.

2023-05-17 15:04 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +  const donorAndFileCountsByExperimentalStrategy = createExperimentalStrategyData(file);
Use `createSqons()`, `createCountsByDataCategoryData()`, `createExperiemtalStrategyData()` to remove repetitive codes from index`.`tsx

2023-05-17 15:21 UTC, joneubank requested changes
Good stuff Dan!

2023-05-17 15:21 UTC, joneubank commented on components/pages/program-entity/gql/DONOR_AND_FILE_COUNT_TABLES_QUERY.ts
> +      quality_control_metrics: aggregations(filters: $SQON_QC) {
This looks pretty reasonable in the end! I was afraid it would look messy but this is good.

2023-05-17 15:21 UTC, joneubank commented on components/pages/program-entity/ProgramCardsLayout/ult.tsx
> +};
What is the name of this file? I don't know what `ult` means. Can we go back to `utils`?

2023-05-17 15:21 UTC, joneubank commented on components/pages/program-entity/ProgramCardsLayout/ult.tsx
> +};
Also, you don't need to export all the functions as an object, just add `export` before each const you want exported.

ex. `export const createExperimentalStrategyData = (file) => {`

2023-05-17 15:21 UTC, joneubank commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +    variables: {
can simplify, no need to deconstruct then list all sqons.
```
  const countsQuerySqons = createSqons(programId);

  const { data: { file = null } = {} } = useQuery(DONOR_AND_FILE_COUNT_TABLES_QUERY, {
    variables: countsQuerySqons
```

or even:

```
  const { data: { file = null } = {} } = useQuery(DONOR_AND_FILE_COUNT_TABLES_QUERY, {
    variables: createSqons(programId)
```

2023-05-17 15:27 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/ult.tsx
> +};
Will change file name! Must be thinking about something else haha! and will add export in front of each `const`

2023-05-17 15:38 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +    variables: {
woo really like this second option, but the values are incorrect for some reason. I think it's caused js asynchronous property. So I used the first option and changed the name to `variables`.
![Screenshot 2023-05-17 at 11 37 23 AM](https://github.com/icgc-argo/platform-ui/assets/79996555/21fcc52c-78b9-4d96-a893-3d269f6702b4)

2023-05-17 15:56 UTC, daniel-cy-lu commented on components/pages/program-entity/index.tsx
>              />
website link shows "undefined" when loading. It now says 'loading'

2023-05-17 15:58 UTC, joneubank commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +    variables: {
I cannot accept a variable called `variables`.

2023-05-17 16:50 UTC, daniel-cy-lu commented on components/pages/program-entity/ProgramCardsLayout/index.tsx
> +    variables: {
using `countsQuerySqons`

2023-05-17 16:58 UTC, joneubank approved these changes

2023-05-17 17:05 UTC, merged