🗺️ #2724 Remove Regions
icgc-argo/platform-ui pull request #2753
Opened 2024-02-09 18:46 UTC by demariadaniel

# Link to Issue
https://github.com/icgc-argo/platform-ui/issues/2724

# Link to Gateway PR:
https://github.com/icgc-argo/platform-api/pull/716

# Description of changes
Removes all references to Region field for programs
- Create Program is not working yet, requires dataCenters added to Query
- Update program showed a success message, but on 2nd login data was unchanged, so this likely requires Program Service updates

## Type of Change

- [ ] Bug
- [ ] Dependency updates
- [ ] Feature
- [x] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [x] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [x] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [x] Manually tested changes
- [x] Added copyrights to new files
- [x] Connected ticket to PR

2024-02-09 19:35 UTC, ciaranschutte requested changes
Unclear about the change to `displayDate` global util

2024-02-09 19:35 UTC, ciaranschutte commented on global/utils/common.tsx
> +
This seems unrelated to the removal of `regions` code throughout. An isolated PR might be good?


I don't quite understand why this change is needed. Is there a bug or ticket we're addressing with it?
GraphQL DateTime seems to be in use for our data ref: https://the-guild.dev/graphql/scalars/docs/scalars/date-time
DateTime is a UTC string eg. `2007-12-03T10:15:30Z`
passing this through `parseInt` is going to terminate at the dash so we'll end up with `2007` and then create a Date object with `200700` which is `Wed Dec 31 1969 19:33:27 GMT-0500 (Eastern Standard Time)` as a Date

If keeping this functionality I think it's more clear as an `if/else`. Nested ternary with multiple `parseInt` and Date constructors is confusing to read for a straightforward `displayDate` util func

2024-02-13 15:03 UTC, ciaranschutte approved these changes
looks good! just a note about generated gql. no changes needed necessarily

2024-02-13 15:03 UTC, ciaranschutte commented on generated/gql_types.tsx
> +   * For lists (Cancer Type, Primary Site, Institution, Countries) the entire new value must be provided, not just values being added.
this file is generated gql from the api - I think the regions have been removed there already? If they haven't this will regenerate with region code

2024-02-13 15:05 UTC, demariadaniel commented on generated/gql_types.tsx
> +   * For lists (Cancer Type, Primary Site, Institution, Countries) the entire new value must be provided, not just values being added.
Yeah sorry this was just find-and-replace carpet bombing, will be updated properly once API is updated

Separate API PR pending review: https://github.com/icgc-argo/platform-api/pull/716

2024-02-13 16:02 UTC, merged