👾 #1098 Update Program data center fixes
icgc-argo/platform-ui pull request #2756
Opened 2024-02-22 19:23 UTC by demariadaniel

# Description of changes

https://app.zenhub.com/workspaces/icgc-argo-platform-dk-production-board-5e542d38415f5034e9fed89d/issues/gh/icgc-argo/roadmap/1098

Adds data center id as default form value
Manage Program Data Center dropdown now shows current Program data center name as placeholder

## Type of Change

- [x] Bug
- [ ] Dependency updates
- [ ] Feature
- [ ] Refactoring
- [ ] Release candidate
- [ ] Styling
- [ ] Testing
- [ ] Other (please describe)

## Checklist before requesting review

- Design (select one):
  - [ ] Matches design:
    - component sizes, spacing, and styles
    - font size, weight, colour
    - spelling has been double checked
  - [ ] No design provided, screenshot of changes included in PR
  - [ ] No changes to UI
- Back-end (select one):
  - [ ] Back-end PRs merged, tested on develop, and linked in this PR
  - [ ] No back-end changes
- [ ] Manually tested changes
- [ ] Added copyrights to new files
- [ ] Connected ticket to PR

2024-02-22 19:55 UTC, ciaranschutte requested changes

2024-02-22 20:01 UTC, demariadaniel commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
`undefined` is the only value which gives us the default appearance like this on the Create Program form:

![Screenshot 2024-02-22 at 2 57 05 PM](https://github.com/icgc-argo/platform-ui/assets/15621876/c965a66b-d972-4def-8a77-99febfd9eab0)

Empty string or null will make this field blank (i.e. no placeholder text)

If we are editing an existing program, then instead we display the dataCenter name by default

2024-02-22 20:06 UTC, ciaranschutte commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
does it work as expected by having a falsy `selectedValue` and not setting the `placeholder`?
https://github.com/icgc-argo/uikit/blob/develop/src/form/Select/index.tsx#L180C11-L180C24

2024-02-22 20:10 UTC, ciaranschutte commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
UIKit API is far from perfect but if we can use it as close as possible to intended it will help for refactoring/upgrades/consistency or worse case expose improvements that need to be made on UIKit itself.

2024-02-22 21:36 UTC, demariadaniel commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
Yes it does in fact: `value={form.dataCenter || undefined}` works just as well!

Can you explain 'use it as close as possible to intended', I saw `placeholder?: string;` and assumed `placeholder: undefined` was intended given the `?`

2024-02-22 21:56 UTC, ciaranschutte commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
For sure! Looking at https://github.com/icgc-argo/uikit/blob/develop/src/form/Select/index.tsx for context.

`placeholder` is trying to be close in functionality to the native HTML placeholder attribute. So when a form control has no value, it has a placeholder value. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder

the `placeHolder` prop in the `Select` component does have an optional type (given the `?`) but if you look here it's getting a default param value https://github.com/icgc-argo/uikit/blob/develop/src/form/Select/index.tsx#L60
That's the reason for the optional type - if you don't give it anything - display something reasonable.

The **_intent_** for this prop is to override the placeholder string value. It's not intended that setting it as `undefined` causes a render to reset the form value. The intended way to "set a form control to have no value" is to use the exposed functions, and then internally the component should display the placeholder is there's no value.

Overriding `placeholder` in this way works but it's not _correct_. It's like hotwiring the component because it's exposing too much of an API.

Does that clarify ` 'use it as close as possible to intended',`?

-------
Ideally, `Select` component in UIkit is improved so the consumer of the component can't even do this and they can only use it in the intended way.

2024-02-22 22:29 UTC, demariadaniel commented on components/pages/submission-system/program-form/ProgramForm.tsx
> +                  placeholder={isEditing ? form.dataCenter : undefined}
Yes, I was definitely thinking "let's hotwire a or b" haha. Rationale makes sense, updated!

2024-02-23 20:44 UTC, ciaranschutte approved these changes

2024-02-23 21:38 UTC, merged